name: XoPlugin
version: '${project.version}'
main: minecraft.xoplugin.XoPlugin
api-version: 1.18
commands:
  challange:
    description: challange player to gane
    usage: /<command>
  accept:
    description: accepted challenge
    usage: /<command>
  deny:
    description: deny the challenge
    usage: /<command>
  put:
    description: put the place in to the table
    usage: /<command>
  save:
    description: save the game
    usage: /<command>
  load:
    description: load the game
    usage: /<command>
