name: minecraftPlugin
version: '${project.version}'
main: minecraft.xoplugin.minecraftPlugin
api-version: 1.18
commands:
  challenge:
    description: challange player to gane
    usage: /<command>
  accept:
    description: accepted challenge
    usage: /<command>
  deny:
    description: deny the challenge
    usage: /<command>
  put:
    description: put the place in to the table
    usage: /<command>
  save:
    description: save the game
    usage: /<command>
  load:
    description: load the game
    usage: /<command>
  destroy:
    description: destroy game board
    usage: /<command>

